[kite]
api_key = your_api_key
api_secret = your_api_secret
redirect_uri = http://127.0.0.1:5000

[google]
sheet_url = https://docs.google.com/spreadsheets/d/your_sheet_id/edit#gid=0

[browser]
chrome_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"  ; optional

[controls]
; true or false
allow_new_stocks = false
; minimum % gap between holding avg and new trigger
min_downside_diff_percent = -3.12
max_upside_diff_percent = 3.12
; maximum INR value allowed per stock
max_holding_value = 50000